language: python
python:
- 3.3
# FIXME: uncomment the following line when Travis CI supports Python 3.4
#        https://github.com/travis-ci/travis-ci/issues/1989
#- 3.4
env:
- secure: "iVXzQqVi5GNRRC8FO7m1pH8np0Wq2/Vf6OSL/4mLbTyiPQ1UGg0hijR4jm5QK7V3rIwpmeE7hsdpjNDpxiCUYefqTJJ258q2AfBIHQzhczM0RttFtmjn8UCOL6Vx7M2nKtzb1BBmv1Rl7Yk0NwzbzUCF8tvr4xM0dGahS1ZH6f0="
services:
- redis-server
install:
- pip install -e .[tests]
script:
- python -mgeofront.version
- py.test -v --durations=20 --redis-host=localhost --github-access-token $GITHUB_ACCESS_TOKEN
