language: python
python:
- 3.3
# FIXME: uncomment the following line when Travis CI supports Python 3.4
#        https://github.com/travis-ci/travis-ci/issues/1989
#- 3.4
install:
- pip install -e .[tests]
script:
- python -mgeofront.version
- py.test -v --durations=20 --redis-host=localhost
