language: python
python:
- 3.3
# FIXME: uncomment the following line when Travis CI supports Python 3.4
#        https://github.com/travis-ci/travis-ci/issues/1989
#- 3.4
env:
- secure: "D2vuD2Zlkd6DD3Nf7EmcgYdaVXg185DqnA44lvXBg8STBe1VQ8koaAj95NrNjQJT2WzejiJEI1AcwNSe6NPjC+0sfq3zdJQlJtKCU/wJytWdi9biqhc4iXVf5lhoHQyd8ehuzX5nmykRi04OzEIFYtO93WQQccSaUSJb2iwWsUM="
services:
- redis-server
install:
- pip install -f https://github.com/spoqa/sftpserver/releases sftpserver==0.2py3  # FIXME
- pip install -e .[tests]
- pip install pytest-cov coveralls
script:
- python -mgeofront.version
- REDIS_HOST=localhost py.test -v --cov geofront --durations=20
after_success:
- coveralls
