language: python
python:
- 3.3
# FIXME: uncomment the following line when Travis CI supports Python 3.4
#        https://github.com/travis-ci/travis-ci/issues/1989
#- 3.4
env:
- secure: "PwuMRTltLgHTUKkLLGOepfAUvsTnn5/KuoPREok4DHIxImN/6MjvtwRucewS55CRkfMMlJ/L0yXeYvIYqW0iIlig6xSYpLV43JelIQHo3NC5CuKVPacFk7od8IHNGE4VRYdnYYTkYh8iGkye0YAOE5627chqYyl6nErrXG/ZzWc="
services:
- redis-server
install:
- pip install -f https://github.com/spoqa/sftpserver/releases sftpserver==0.2py3  # FIXME
- pip install -e .[tests]
- pip install pytest-cov coveralls
script:
- python -mgeofront.version
- REDIS_HOST=localhost py.test -v --cov geofront --durations=20
after_success:
- coveralls
