language: python
python:
- 3.3
- 3.4
env:
- secure: "jZVzNDRii4P1ay6FIlzMbuIVE2u4o4trSwWD09G0MVLv1PLbv05a4ToDjwYv7b8hcOeTIUAUHtTNaaIwuPf256OUhpmRoROy/XkdShZGh5pw4RrTH2Pgo3hxjRN011AzcUmVoiw68hYHSN9yzVZHhtVrKKwXP2H96Aae6BTmCPA="
services:
- redis-server
install:
- pip install -f https://github.com/spoqa/sftpserver/releases sftpserver==0.2py3  # FIXME
- pip install -e .[tests]
- pip install --allow-external mysql-connector-python --allow-unverified mysql-connector-python psycopg2 PyMySQL mysql-connector-python
- pip install pytest-cov coveralls
before_script:
- createdb -U postgres -E utf8 -T postgres geofront_test
- mysql -e 'CREATE DATABASE geofront_test;'
script:
- python -mgeofront.version
- REDIS_HOST=localhost PGDATABASE=geofront_test PGUSER=postgres MYSQL_DATABASE=geofront_test MYSQL_HOST=localhost MYSQL_USER=root py.test -v --cov geofront --durations=20
after_success:
- coveralls
