language: python
python:
- 3.3
# FIXME: uncomment the following line when Travis CI supports Python 3.4
#        https://github.com/travis-ci/travis-ci/issues/1989
#- 3.4
env:
- REDIS_HOST=localhost
- secure: "iVXzQqVi5GNRRC8FO7m1pH8np0Wq2/Vf6OSL/4mLbTyiPQ1UGg0hijR4jm5QK7V3rIwpmeE7hsdpjNDpxiCUYefqTJJ258q2AfBIHQzhczM0RttFtmjn8UCOL6Vx7M2nKtzb1BBmv1Rl7Yk0NwzbzUCF8tvr4xM0dGahS1ZH6f0="
services:
- redis-server
install:
- pip install -f https://github.com/spoqa/sftpserver/releases sftpserver==0.2py3  # FIXME
- pip install -e .[tests]
- pip install pytest-cov coveralls flake8
script:
- python -mgeofront.version
- flake8
- py.test -v --cov geofront --durations=20
after_success:
- coveralls
